### ISSUE TITLE
Куда пропали эти кнопки?

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#18]
_**Это ишус ко второму макету**_
![image](https://user-images.githubusercontent.com/26929933/31171686-cdc23e06-a92a-11e7-9158-4afa3839b5ad.png)

**Comment by kinda-neat** [comment]
Это состояние кнопки при :hover, разве не логично?

**Comment by Zarwlar** [comment]
Окей, я не заметил, что они изменяются по hover'у
