### ISSUE TITLE
circle-progress-bar-b

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#19]
Он явно не соответствует макету

![image](https://user-images.githubusercontent.com/26929933/31171752-141cd956-a92b-11e7-8a20-decffa49e31f.png)

**Comment by Zarwlar** [comment]
И в других местах тоже это нужно исправить

**Comment by kinda-neat** [comment]
Насчет желтого прогресс бара, так там в либе происходит перерисовка под разную ширину экрана, т.е. страница загрузилась -> круг отрисовался -> теперь если zoom в браузере менять, то действительно он будет размазанный, но если перезагрузить страницу с выставленным zoom, то все норм перерисуется (гифка ниже). Также Серега разрешил оставить такой размер шрифта который на данный момент в этом блоке. А насчет последнего pie-chart согласен, он поехал, буду исправлять)
![issue2](https://user-images.githubusercontent.com/27883524/31417864-8229d44a-ae5c-11e7-9272-5d93ae9738e9.gif)
![image](https://user-images.githubusercontent.com/27883524/31417666-46b41d40-ae5b-11e7-97ce-7f2a632b953f.png)
![image](https://user-images.githubusercontent.com/27883524/31417671-50a9fc3e-ae5b-11e7-9b72-9b7a1637bdc7.png)

**Comment by Zarwlar** [comment]
Хорошо, оставляем, как есть :)
