### ISSUE TITLE
Подстраивание сайта под макет

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#21]
_**Это ишус ко второму макету**_
Как правило, мы берём макет, загружаем его в PixelPerfect и задаём ему определённый масштаб, чтобы проверить вёрстку. Но в твоём случае приходиться изменять зум окна страницы, чтобы подогнать его под макет. Это нужно исправить.

Т.е. при открытии окна должно быть что-то такое:

![image](https://user-images.githubusercontent.com/26929933/31172234-f9ece79a-a92c-11e7-840a-30f6ea68d077.png)

Но точно не так:

![image](https://user-images.githubusercontent.com/26929933/31172138-8e07286a-a92c-11e7-90ef-ac39043a2f4c.png)

**Comment by kinda-neat** [comment]
Т.е. ты хочешь сказать что кнопки должны быть в том порядке, что на макете (в линию, а не как у меня, друг под другом), верно?

**Comment by Zarwlar** [comment]
Вообще - да, но сейчас речь не об этом. У тебя сами элементы на странице очень большого размера, нужно скролить твою страницу, чтобы она встала под макет

**Comment by kinda-neat** [comment]
А какая ширина у твоей картинки? Я вытащил из psd картинку с шириной 1280 и вот результат
![image](https://user-images.githubusercontent.com/27883524/31184206-f46f548a-a952-11e7-9040-20d734556a5f.png)

**Comment by Zarwlar** [comment]
Ширина должна быть 700px, как у макета. Не обязательно использовать PixelPerfect что бы увидеть, что ширина окна в вёрстке должна быть 700px

**Comment by kinda-neat** [comment]
Вообщем да, фигово немного получилось. Серега потенциально не против (скрин ниже, также в телеграмме могу переслать сообщение), смотри, если вставить оригинальную картинку, то нужно ее увеличить в 1280/700 = 1.82857 раз и все будет ок
![image](https://user-images.githubusercontent.com/27883524/31384413-1b2b9d00-ade9-11e7-95bf-7ca49d2c072e.png)

**Comment by Zarwlar** [comment]
Хорошо, пусть будет так)
