### ISSUE TITLE
Ссылка на изображение

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/task-two-cv#22]
`img.developer-card__image(src=""+data.card.image+"" alt="developer's avatar")`
Интересно, что за пустые строки в src )

**Comment by kinda-neat** [comment]
Если перед data.card.image они действительно лишние, то те что после,  они есть потому что у меня пропадает подсветка следующего атрибута :) понятное дело что там подставляется строка, но все же. Убрать или оставить?
![issue](https://user-images.githubusercontent.com/27883524/31348861-27d21ab4-ad4b-11e7-8ad0-1239ed1e74dd.gif)

**Comment by shevdi** [comment]
Так это просто IDE не видит. Подобные косяки могут встречаться иногда. Если все нормально работает, то лучше удалить.
