### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by shevdi** [Maksimus-Prime/task-two-cv#24]
В макете не Arial шрифт. Там подключается свой.

**Comment by kinda-neat** [comment]
Он платный, поэтому оставил Arial. Кстати все договоренности с Серегой относительно верстки в силе? Он разрешил использовать здесь Arial, а практику по шрифтам оставить на второй макет.

**Comment by shevdi** [comment]
Хорошо. Уточнил у Сереги
