### ISSUE TITLE
Не использовать фиксированные значения для выравнивания

### ISSUE THREAD

**Issue by Burize** [Maksimus-Prime/task-two-cv#25]
Ни для горизонатльного, ни для вертикального. Делать все максимально гибко, и чтобы не было захардкоженных значений.

Например, в header.less `top: 45%;`: он сейчас и не выравнен по вертикали - просто подогнан, а если ты захочешь потом сделать линии толще (особенно если значение будет в px или rem), тебе придется менять значение `top`

**Comment by kinda-neat** [comment]
Исправил момент с header.less. Посмотри плиз, могу закрывать issue?
