### ISSUE TITLE
Различные плагины должны использоваться из node_modules

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#27]
Сейчас в твоих скриптах используются плагины, которые должны быть установлены глобально) Чтобы это исправить, нужно изменить пути запуска плагинов на локальные (node_modules)

Лучше сразу поправить во всех проектах :)
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "npm i": "npm install",
>     "prod": "webpack -p",
>     "dev": "webpack-dev-server"
>   }

**Comment by kinda-neat** [comment]
Понял, плиз посмотри, сейчас это выглядит как надо? Во всех остальных проектах появится с следующим коммитом)

**Comment by Zarwlar** [comment]
Да, теперь ок)
