### ISSUE TITLE
Данные не должны струтурно зависеть от верстки

### ISSUE THREAD

**Issue by Znack** [Maksimus-Prime/task-two-cv#29]
У тебя сейчас структура данных жескто завязана на том, как в верстке это выглядит, но это мягко говоря неадекватно. Ты же не будешь в базе делить данные на две таблицы с одинаковой структуруой, просто потому что выводятся данные в двух колонках визуально разных. И что за блок `card` в data.json? Почему инфа о профиле и описание профиля разделены? Опять же, только потому тчо в верстке это два разных блока? :)

**Comment by kinda-neat** [comment]
Увидел, особенно ярко это проявляется в блоке software) Да, о profile и card так и думал, объединю в один)
