### ISSUE TITLE
Добавить README

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#3]
Добавить README c описанием проекта и командами его запуска. 
После этого, попробуй склонировать свой проект с гитхаба и запустить
согласно инструкции, которой ты написал.
Если всё ок - закрывай ишус

**Comment by kinda-neat** [comment]
Fixed

**Comment by Zarwlar** [comment]
`"npm i": "npm install"` Стандартная команда npm, не нужно её прописывать. Её можно считать промежуточным шагом к запуску твоего проекта.
Т.е.
1. Команда для клонирования репозитория (есть)
2. npm i (есть)
3. a) Запуск на dev. - здесь должен запускаться какой-нибудь webpack-dev-server, например, с ключом watch (нету)
b) Получение production build'a - здесь мы должны получить, например, минифицированный css, js (нету)

**Comment by kinda-neat** [comment]
Для dev может быть я просто запущу webpack в режиме watch, потому что webpack-dev-server здесь никак не использовался, а на prod я получу минифицированный css, js, норм будет?

**Comment by Zarwlar** [comment]
C production - ок.
Dev разработка должна вестись на собственном локальном сервере, потому что, как минимум, при разработке через одни лишь локальные файлы не будут видны проблемы, вызванные отсутствием сервера, например, http запросы в скриптах и т.п.

**Comment by kinda-neat** [comment]
Ок, смотри у меня есть сборка через webpack где без минификации собираются css, js, есть запуск webpack -p, где webpack сам минифицирует css и js, а так же есть webpack-dev-server. Webpack-dev-server не бандлит в папку а хранит результат в памяти, тогда как быть? Мне нужно 1) чтобы при dev мне собрался этот неминифицированный css, js и при этом 2) нужен еще webpack-dev-server. Норм будет если опустить момент 1), где будет подразумеваться, что при надобности сам запустишь webpack, и оставить в dev - webpack-dev-server, а в prod - webpack -p?

**Comment by kinda-neat** [comment]
Плиз, посмотри могу ли закрывать issue?

**Comment by Zarwlar** [comment]
Пока нет.
Я проследовал инструкция из README, и у меня всё равно не получилось запустить (npm run dev):
![image](https://user-images.githubusercontent.com/26929933/31046454-e745f4a4-a622-11e7-9e86-ed99da81b8eb.png)

**Comment by Maksimus-Prime** [comment]
Добавил лоадеры прошедшие мимо --save-dev, мой косяк. Попробуй еще раз

**Comment by kinda-neat** [comment]
Добавил ускользнувшие от --save-dev лоадеры, мой косяк. Попробуй еще раз

**Comment by kinda-neat** [comment]
Ну так что там?

**Comment by Zarwlar** [comment]
Не запускается

![image](https://user-images.githubusercontent.com/26929933/31162947-3a792da0-a90a-11e7-9a02-aa1b933025ec.png)

**Comment by Zarwlar** [comment]
Вообще, давай ещё раз, как было сказано в начале.
Должно выполняться условие:

> попробуй склонировать свой проект с гитхаба и запустить
согласно инструкции, которой ты написал.

Посмотрите внимательнее на зависимости. Возможно, где-то имеется глобальная зависимость, которая не указана в проекте или ещё что-нибудь в этом духе. Всё это будет приводить к тому, что я не смогу запустить проект на своей машине

**Comment by kinda-neat** [comment]
Посмотрел еще раз. вот смотри, что у меня глобально стоит:
(выполнил команду npm list -g --depth=0)
![image](https://user-images.githubusercontent.com/27883524/31450614-142b24f8-aed4-11e7-80a4-15af79cc103c.png)
У тебя, как я понял, не может найти модуль pug. Pug есть в зависимостях
![image](https://user-images.githubusercontent.com/27883524/31450687-43397e20-aed4-11e7-977c-242237296695.png)
Пожалуйста попробуй еще раз, просто я уже не знаю в чем еще может быть проблема :(
все глобальные зависимости которые касались или могли касаться проекта почистил

**Comment by Zarwlar** [comment]
В ветке master всё работает, а в рефакторинге - крашится 
![image](https://user-images.githubusercontent.com/26929933/31495534-27cd397a-af82-11e7-9095-fd26ebcc047c.png)

**Comment by kinda-neat** [comment]
Так и должно быть :)
Я когда клонировал репу, тестил свою инструкцию, в один из этих тестов я забыл переключиться на ветку refactoring, запушил коммит в мастер и потом пошли траблы с пушем в ветку refactoring, написал Сереге, и по итогу продолжил пушить в мастер
![image](https://user-images.githubusercontent.com/27883524/31500031-99950458-af90-11e7-9da2-7d1a955779f4.png)

**Comment by Zarwlar** [comment]
Окей)
