### ISSUE TITLE
Общие замечания по стилям

### ISSUE THREAD

**Issue by Zarwlar** [Maksimus-Prime/task-two-cv#6]
Мы работаем по БЭМу, поэтому:
1) Нужно убрать li, span, img и заменить их на соответствующие классы;
2) Нужно убрать каскады, иерархия селекторов должна быть плоской.

Помимо БЭМа:
1) В .developer-education и .skills-item заменить у padding'ов px-ли на другие
величины.

**Comment by Maksimus-Prime** [comment]
Касательно 1. Как быть с ситуациями, когда нужен этот несчастный span внутри h1 чтобы применить какой-нибудь css-trick, где h1 уже является элементом компонента, то как тогда быть? согласно правилу "!Все теги идут только с классами - никаких пустых <div>, <section> и тд. Но можно для инлайновых элементов, если есть четкое понимание зачем. Это очень сильно мешает новым людям входить в проект и вам через некоторое время разобраться в собственной верстке", я думаю могу так оставить, из-за того что span - инлайновый элемент и есть четкое понимание зачем (реализовать css-trick).

**Comment by Maksimus-Prime** [comment]
Хочу прояснить сразу насчет задания модификаторов, с less в этом плане возникли траблы, подробнее я писал в риззоме
https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_815b1/

**Comment by kinda-neat** [comment]
Посмотри плиз. Могу закрывать issue?

**Comment by Zarwlar** [comment]
Да
